#Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

#Triangle         Tn=n(n+1)/2         1, 3, 6, 10, 15, ...
#Pentagonal         Pn=n(3n−1)/2         1, 5, 12, 22, 35, ...
#Hexagonal         Hn=n(2n−1)         1, 6, 15, 28, 45, ...
#It can be verified that T285 = P165 = H143 = 40755.

#Find the next triangle number that is also pentagonal and hexagonal.

def triangle(number)
    number * (number+1) / 2
  end
  
  def pentagonal(number)
    number * (number*3-1) / 2 
  end
  
  def hexagonal(number)
    number * (2*number-1)
  end
  
  (20000..100_000).each do |t|
      puts t
      (165..t).each do |p|
          if pentagonal(p) == triangle(t)
              (143..p).each do |h|
                  if pentagonal(p) == hexagonal(h)   
                      puts "t: #{t}, p: #{p}, h: #{h}"
                  end
              end
          end
      end
  end
  
  puts triangle(285)
  puts pentagonal(165)
  puts hexagonal(143)
